<a href="https://colab.research.google.com/github/EshantDazz/Deep-Learning/blob/main/TensorFlow/Fundamentals/Getting_Started_with_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **<center><font color='clue'>Getting Started with Tensors</font></center>**

- Introduction to Tensors
- Getting information from tensors
- Manipulating Tensors
- Tensors and Numpy
- Using @tf.function ( a way to speed up your regular Python functions)
- Using GPU with TensorFlow( or TPUs)

## **Introduction to Tensorflow**

In [ ]:
import tensorflow as tf

In [ ]:
tf.__version__

'2.11.0'

In TensorFlow, tf.constant and tf.Variable are two different ways to create tensors with different properties.

tf.constant creates a tensor whose value cannot be changed once it is defined. It is used for storing constant values that are not expected to change during training, such as hyperparameters or fixed input data. tf.constant takes a Python object as input and returns a tensor with the same value.<br>

tf.Variable creates a tensor whose value can be changed during training. It is used for storing variables that are expected to change during training, such as weights and biases in a neural network. tf.Variable takes an initial value as input and returns a tensor with the same shape and type as the input.

### <font color='pink'>**tf.constant**</font>

In [ ]:
#Creating tensors with tf.constant()
scaler=tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#Checking the number of dimensions of the tensor
scaler.ndim

0

In [ ]:
#Creating a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
#Creating a matrix
matrix=tf.constant([[10,7],
                    [23,27]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [23, 27]], dtype=int32)>

In [ ]:
matrix.ndim

2

**Tensor**: It is basicallty an n dimensional array

### <font color='pink'>**tf.Variable**</font>

In [ ]:
#Creating a tensor with tf.variable
variable_tensor=tf.Variable([[23,43],[45,67]])
variable_tensor

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[23, 43],
       [45, 67]], dtype=int32)>

In [ ]:
static_tensor=tf.constant([[23,43],[45,67]])

In [ ]:
print(variable_tensor,static_tensor)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[23, 43],
       [45, 67]], dtype=int32)> tf.Tensor(
[[23 43]
 [45 67]], shape=(2, 2), dtype=int32)


In [ ]:
#Changing the value of a variable_tensor
variable_tensor[0].assign(13)
variable_tensor

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[13, 13],
       [45, 67]], dtype=int32)>

In [ ]:
#The same thing won't work with the static or unchangable tensor even when we use assign

### <font color='pink'>**Creating Random Tensors**</font>

Random tensors are tensors of some abitary size which contains some numbers

In [ ]:
#Creating Random tensors
r1=tf.random.Generator.from_seed(69)
r1

In [ ]:
r1=r1.normal(shape=(3,2))
r1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.29164317,  1.4531525 ],
       [-0.8223833 , -1.3446563 ],
       [-0.7183838 , -0.20373915]], dtype=float32)>

In [ ]:
#Shuffling the orders of tensors
"""
From Video:
To mix up all the pizza and ramen so that it does not get all the pizza value first and then ramen
"""

#That is why we shuffle a tensor

'\nFrom Video:\nTo mix up all the pizza and ramen so that it does not get all the pizza value first and then ramen\n'

In [ ]:
not_shiffled=tf.constant([[10,4],
                          [5,6],
                          [90,34]])

#Shuffle our non-shuffled tensor
tf.random.shuffle(not_shiffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[90, 34],
       [10,  4],
       [ 5,  6]], dtype=int32)>

In [ ]:
#Using seed
tf.random.set_seed(30)
tf.random.shuffle(not_shiffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  4],
       [90, 34],
       [ 5,  6]], dtype=int32)>

In [ ]:
#Using global seed and operation level seed in order to keep our shuffled tensors in the same order
tf.random.set_seed(30)
tf.random.shuffle(not_shiffled,seed=30)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[90, 34],
       [10,  4],
       [ 5,  6]], dtype=int32)>

### <font color='pink'>**Creating Tensors from Numpy Array**</font>

In [ ]:
#Teensor of all ones
tf.ones([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape=(3,4),dtype=tf.int32)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)>

-  <font color='yellow'>**The main difference between Numpy arrays and TensforFlow tensors is that tensors can be run on a GPU(much faster than numerical computing)**</font>

In [ ]:
import numpy as np
a=np.arange(1,25,dtype='int32')
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A=tf.constant(a)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
#Changing the shape and dimension of it
A=tf.constant(a,shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
A.ndim

3

### <font color='pink'>**Getting Information from your tensors**</font>

- Shape
- Dimension
- Axis or dimension
- Size

In [ ]:
#Rank or Dimension 4 tensors
rr=tf.zeros(shape=(2,3,4,5),dtype=tf.int32)
rr

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]],


       [[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]]], dtype=int32)>

In [ ]:
print("Shape= ",rr.shape)
print("Dimension=  ",rr.ndim)
print("Size = ",tf.size(rr))
print("Size in numpy= ",tf.size(rr).numpy())
print("Dtype = ",rr.dtype)

Shape=  (2, 3, 4, 5)
Dimension=   4
Size =  tf.Tensor(120, shape=(), dtype=int32)
Size in numpy=  120
Dtype =  <dtype: 'int32'>


### <font color='pink'>**Indexing and Appending Tensors**</font>

In [ ]:
rr

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]],


       [[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]]], dtype=int32)>

In [ ]:
rr[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]]], dtype=int32)>

In [ ]:
rr[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=int32, numpy=array([[[[0, 0, 0, 0, 0]]]], dtype=int32)>

In [ ]:
rr[:1,:1,:1,:].numpy()

array([[[[0, 0, 0, 0, 0]]]], dtype=int32)

In [ ]:
#Creating a rank 2 tensor
rr=tf.constant([[10,7],
                [45,6]])

In [ ]:
print("Shape= ",rr.shape)
print("Dimension=  ",rr.ndim)
print("Size = ",tf.size(rr))
print("Size in numpy= ",tf.size(rr).numpy())
print("Dtype = ",rr.dtype)

Shape=  (2, 2)
Dimension=   2
Size =  tf.Tensor(4, shape=(), dtype=int32)
Size in numpy=  4
Dtype =  <dtype: 'int32'>


In [ ]:
##Getting the last item of each row
rr[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 6], dtype=int32)>

In [ ]:
rr

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [45,  6]], dtype=int32)>

In [ ]:
####Adding an extra dimension to our rank 2 tensor
rr2=rr[...,tf.newaxis]
rr2

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[45],
        [ 6]]], dtype=int32)>

In [ ]:
##Alternative to tf.newaxis
tf.expand_dims(rr,axis=-1) #'-1' means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[45],
        [ 6]]], dtype=int32)>

In [ ]:
tf.expand_dims(rr,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [45,  6]]], dtype=int32)>

In [ ]:
tf.expand_dims(rr,axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[45,  6]]], dtype=int32)>

### <font color='pink'>**Manipulating Tensors with basic operation**</font>

**Basic Operations**
`+,-,*,/`

In [ ]:
tt=tf.constant([[10,7],
                [4,5]])
tt

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 4,  5]], dtype=int32)>

In [ ]:
tt+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [14, 15]], dtype=int32)>

In [ ]:
tt*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 40,  50]], dtype=int32)>

In [ ]:
tt-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-6, -5]], dtype=int32)>

In [ ]:
tt/10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.4, 0.5]])>

In [ ]:
#Let us use tenserflow  built in function too
tf.multiply(tt,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 40,  50]], dtype=int32)>

### <font color='pink'>**Matrix Multiplication**</font>

In [ ]:
tt

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 4,  5]], dtype=int32)>

In [ ]:
#Using matmul function
tf.matmul(tt,tt)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[128, 105],
       [ 60,  53]], dtype=int32)>

In [ ]:
#Using python operator @
tt@tt

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[128, 105],
       [ 60,  53]], dtype=int32)>

In [ ]:
#Reshaping Function

In [ ]:
rr=tf.ones(shape=(2,3))
rr

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
tf.reshape(rr,shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [ ]:
#Transpose Operation

In [ ]:
rr

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
tf.transpose(rr)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

### <font color='pink'>**Changing Dataype**</font>

In [ ]:
A=tf.constant([[1.2,4.6],
               [2.6,12.3]])
A

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.2,  4.6],
       [ 2.6, 12.3]], dtype=float32)>

In [ ]:
a=tf.cast(A,dtype=tf.float16)
a

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[ 1.2,  4.6],
       [ 2.6, 12.3]], dtype=float16)>

In [ ]:
a.dtype

tf.float16

### <font color='pink'>**Aggregation**</font>

In [ ]:
#Absolute values
D=tf.constant([-2,-3])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-2, -3], dtype=int32)>

In [ ]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [ ]:
E=tf.constant(np.random.randint(1,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([42, 28, 51, 44, 44, 47, 78, 48, 28, 23, 95, 86, 14, 70, 38,  4, 86,
       72, 96, 55, 59, 82, 97, 12, 29, 23, 40, 87, 25, 15, 90, 67, 49, 49,
       85, 82, 51, 43, 19, 22, 58, 80, 70, 62, 53, 21,  1, 65, 70, 88])>

In [ ]:
##min 

In [ ]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
#Max

In [ ]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [ ]:
#Mean

In [ ]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=52>

In [ ]:
#Sum

In [ ]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2643>

In [ ]:
#Variance and standard deviation

In [ ]:
import tensorflow_probability as tfp #We need tensorflow stats for variance

In [ ]:
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=709>

In [ ]:
tf.math.reduce_variance(tf.cast(E,dtype=tf.float64))

<tf.Tensor: shape=(), dtype=float64, numpy=708.6004>

In [ ]:
tf.math.reduce_std(tf.cast(E,dtype='float64'))

<tf.Tensor: shape=(), dtype=float64, numpy=26.619549207302516>

## <font color='pink'>**Finding the positional maximum and minimum**</font>

In [ ]:
tf.random.set_seed(42)
F=tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
#Finding positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
#Index on the largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
#Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

## <font color='pink'>**Squeezing a tensor(removing all single dimensions)**</font>

In TensorFlow, the tf.squeeze() function is used to remove dimensions of size 1 from a tensor. This can be useful in various situations, such as when you want to reduce the rank of a tensor or when you want to remove any extra dimensions that may have been introduced by a previous operation.

In [ ]:
tf.random.set_seed(42)
G=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
          0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
          0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
          0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
          0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
          0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
          0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
          0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
          0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
          0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]],
      dtype=float32)>

In [ ]:
G_squeeze=tf.squeeze(G)
G_squeeze

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

## <font color='pink'>**One Hot Encoding**</font>

In [ ]:
#Create a list of indices
some_list=[0,1,2,3]     #could be red,blue,green,yellow


#one hot encode of our list
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
#specify custom values for one hot encoding
tf.one_hot(some_list,depth=4,on_value='Deep learning is fun',off_value='Life is tough')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Deep learning is fun', b'Life is tough', b'Life is tough',
        b'Life is tough'],
       [b'Life is tough', b'Deep learning is fun', b'Life is tough',
        b'Life is tough'],
       [b'Life is tough', b'Life is tough', b'Deep learning is fun',
        b'Life is tough'],
       [b'Life is tough', b'Life is tough', b'Life is tough',
        b'Deep learning is fun']], dtype=object)>

## <font color='pink'>**More Maths Function**</font>

- Square
- Log
- Square Root

In [ ]:
H=tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
H.numpy()

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [ ]:
#Square
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
#Finding the SquareRoot
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
#Log Function
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## <font color='pink'>**Numpy and Tensors**</font>

In [ ]:
J=tf.constant(np.array([2.,3.,7.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 3., 7.])>

In [ ]:
#Converting our tensor back to array
np.array(J)

array([2., 3., 7.])

In [ ]:
#Accessing the element
J=tf.constant([3.])
print(J.numpy())
J.numpy()[0]

[3.]


3.0

In [ ]:
#The default types of each are different
numpy_J=tf.constant(np.array([3.,4.,5.]))
tensor_J=tf.constant([3.,4.,5.])

In [ ]:
#Checking the datatypes of each
print(numpy_J.dtype)
print(tensor_J.dtype)

<dtype: 'float64'>
<dtype: 'float32'>


## <font color='pink'>**Finding access to GPUs**</font>

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [ ]:
tf.config.list_physical_devices("GPU")

[]

In [ ]:
#We do not have accesS

In [ ]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Thu Mar 16 19:37:27 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   55C    P8     9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------